### ISSUE TITLE
error where run "npm test" 

### ISSUE THREAD

**Issue by eltonlaice** [paymentsds/mpesa-js-sdk#37]
Node v12.16.1... 

Error console: 
> @paymentsds/mpesa@0.1.0-alpha-4 test /home/elton/Documents/paymentsds/mpesa-js-sdk
> mocha

Error: Not supported
    at formattedImport (/home/elton/.npm-global/lib/node_modules/mocha/lib/esm-utils.js:6:23)
    at Object.exports.requireOrImport (/home/elton/.npm-global/lib/node_modules/mocha/lib/esm-utils.js:23:14)
    at Object.exports.loadFilesAsync (/home/elton/.npm-global/lib/node_modules/mocha/lib/esm-utils.js:33:34)
    at Mocha.loadFilesAsync (/home/elton/.npm-global/lib/node_modules/mocha/lib/mocha.js:421:19)
    at singleRun (/home/elton/.npm-global/lib/node_modules/mocha/lib/cli/run-helpers.js:156:15)
    at exports.runMocha (/home/elton/.npm-global/lib/node_modules/mocha/lib/cli/run-helpers.js:225:10)
    at Object.exports.handler (/home/elton/.npm-global/lib/node_modules/mocha/lib/cli/run.js:366:11)
    at /home/elton/.npm-global/lib/node_modules/mocha/node_modules/yargs/lib/command.js:241:49
npm ERR! Test failed.  See above for more details.

**Comment by edsonmichaque** [comment]
@eltonlaice, the error is legit, let us change the requirements to the latest active LTS (v12) for production purposes. 
For development purposes we recommed the latest version of Node.js, I will update the documentation to reflact these recomendations.
