### ISSUE TITLE
MissingPropertiesError: There are attributes missing to complete the transaction

### ISSUE THREAD

**Issue by eltonlaice** [paymentsds/mpesa-js-sdk#46]
This should be the array for the request. 
`
const paymentData = {
   from: '841234567',               // input_CustomerMSISDN
   reference: '11114',              // input_ThirdPartyReference
   transation: 'T12344CC',          // input_TransactionReference
   amount: '10'                     // input_Amount
};
`
But I have this error.

`
     MissingPropertiesError: There are attributes missing to complete the transaction
      at Service.handleRequest (file:///home/elton/Documents/paymentsds/js-sdk/src/service.js:71:13)
      at Service.handleSend (file:///home/elton/Documents/paymentsds/js-sdk/src/service.js:46:17)
      at Client.send (file:///home/elton/Documents/paymentsds/js-sdk/src/client.js:13:25)
      at Context.<anonymous> (file:///home/elton/Documents/paymentsds/js-sdk/test/client.js:83:16)
      at processImmediate (internal/timers.js:456:21)
`

**Comment by edsonmichaque** [comment]
@eltonlaice can you please share your client configuration?
